FROM python:3.9.2-buster

WORKDIR /project/backend

COPY ./requirements.txt ./requirements.txt

RUN pip3 install -r requirements.txt

COPY . . 

# Setting the python path inside the container 
ENV PYTHONPATH /project/backend

EXPOSE 3000
